CREATE TABLE aantekeningen (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `user` INT NOT NULL,
  `tekst` TEXT,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
)